version: '3'
networks:
  mynetwork:
    driver: bridge

services:
  timescaledb:
    image: "timescaledb:1.2.1"
    build: ./timescaledb/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=123456
    networks:
      mynetwork:
        aliases:
          - local.timescaledb.com
