version: '3'
networks:
  mynetwork:

services:
  timescaledb:
    image: "timescaledb:1.2.1"
    build: ./timescaledb/
    ports:
      - "5432:5432"
    networks:
      - mynetwork
  
  #pulsar:
  #  image: "pulsar:2.4.0"
  #  build: ./pulsar/
  #  ports:
  #    - "8080:8080"
  #    - "6650:6650"
  #  networks:
  #    - mynetwork
